apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-javaee-app-deployment
  labels:
    app: my-javaee-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-javaee-app
  template:
    metadata:
      labels:
        app: my-javaee-app
    spec:
      containers:
      - name: my-javaee-app-container
        image: my-javaee-app-image
        ports:
        - containerPort: 8081
